### PR TITLE
Update install instructions and install script for Mac OS.

### LINKED ISSUE #81: no module name usb 1
I got it it installed on a Mac 10.13.6 

the machine is connected with the usb and usb.core.find() gives me thins

<DEVICE ID 0b4d:112b on Bus 020 Address 007>

and usb.version_info[0] gives me 1

I get this error when I run the plugin in inkscape .. 

thanks for any help

Screenshot 2019-03-25 21 59 57

### PR DESCRIPTION
**Pull request by tschamm**
Update install instructions and install script for Mac OS.
* Install python3 via brew
* Use pip3 to install dependencies (easy_install is deprecated)
* Update user extension dir.
* Fixes #81 and #126

### CODE REVIEW

**Comment by tschamm** [comment]
I'm aware this PR would drop python2 support on Mac OS. 

If python2 support is still needed on Mac OS, we have to look for a solution on how to find a compatible version of python2 libusb package and the libusb dylib installed by `homebrew`.

**Comment by t0b3** [comment]
@jtebert can you try if this proposed solution works for your setup?

**Comment by jtebert** [comment]
Thanks for making these updates.

There seems to be just one change necessary for this to install correctly. When I try to install and run it as is, it complains that numpy is not installed. If I install numpy it appears to work. (I'm not with the cutter to confirm that it cuts correctly, but the only error I now get is that it can't find the plotter.)

I believe that adding numpy to the requirements.txt should fix this.

One other small suggestion -- it might be useful to give more detailed instructions in-line in the readme about how to update the Inkscape python interpreter.

**Comment by tschamm** [comment]
Any update on this? The comments from @jtebert were addressed by the commits done on Feb, 9th.

**Comment by t0b3** [comment]
@tschamm thanks for this contribution

**Pull request merged**
