### PR TITLE
Fix multi-action dialogs

### PR DESCRIPTION
**Pull request by the-jesus**
This fixed the problem with the confirmation dialog of the multi-action dialog. Also fixing that presets couldn't be deleted.

### CODE REVIEW

**Comment by t0b3** [comment]
double check you committed everything and tested it thouroughly...
```
Traceback (most recent call last):
  File "~/.config/inkscape/extensions/silhouette_multi.py", line 33, in <module>
    from silhouette.Dialog import Dialog
ModuleNotFoundError: No module named 'silhouette.Dialog'
```

**Comment by the-jesus** [comment]
Yeah, don't know why, but I must have forgotten to check in the file. I have never programmed python before, tbh. So I hope it works now.

**Comment by t0b3** [comment]
running with this PR leads to
```
Traceback (most recent call last):
  File "/home/thomas/.config/inkscape/extensions/silhouette_multi.py", line 33, in <module>
    from silhouette.Dialog import Dialog
  File "/home/thomas/.config/inkscape/extensions/silhouette/Dialog.py", line 1, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
```
seems like there is no clean error handling implemented for cases w/o wx. can you reorder the imports and softfail with some more meaningful msg?

... and obviously you need to tweak your code to pass the tests

PS: can you elaborate on what exact problem this PR fixes? feel free to report an issue on that... THX

**Comment by the-jesus** [comment]
Please excuse me for making so much work. I now try to deal with the errors regarding the missing `wx` library.
The changes should fix the issue with the dialogs of the multi action. The "preset delete" and the "execute" doesn't work. This problem is mentioned here: #213
So please give it another try.

**Comment by t0b3** [comment]
@the-jesus thank you for your work and your explanations
@gwhitney can you review this PR?

**Comment by gwhitney** [comment]
Haven't used inkscape-silhouette in a while (haven't happened to need to cut anything intricate) but would be happy to give this a spin. However, I am busy through Thanksgiving weekend -- can it wait until the following week?

**Comment by the-jesus** [comment]
Hi, how have you been?
Here is just a quick reminder. :stuck_out_tongue_closed_eyes:

**Pull request merged**
