### PR TITLE
Test multi nogui

### PR DESCRIPTION
**Pull request by gwhitney**
This PR adds a "-p" option to silhouette_multi.py to specify the pickle file of stored settings, refactors all of the color separation settings processing to separate it from the wx gui code and moves the wx code into a separate file, and adds a "-g" option to control whether the GUI is used. (If not, it simply loads the pickle file and generates the commands to run based on the default
settings therein.)

It then uses these new options to add a test that silhouette_multi.py runs without the GUI and generates an appropriate color separation.

This at least partially addresses #157.

### CODE REVIEW

**Comment by gwhitney** [comment]
Aha the failed tests are due to things like newline versus carriage-return and newline when comparing the actual and proper output, and some extra stuff written to stderr on some of the systems. I will fix and push another commit.

**Comment by t0b3** [comment]
@gwhitney thanks for your great work. unfortunately I didn't manage to get an in depth look at it yet.
may I ask you to adapt some minor things?
- add the new multi related tests in a separate `run_multi.py` file for better separation and easier overview
- move the data related to the new tests in a subfolder within `test` to keep the related data together

this would be helpful

**Comment by gwhitney** [comment]
Done as requested.

**Comment by t0b3** [comment]
LGTM

**Pull request merged**
