### PR TITLE
Updated Commands of GP-GL (+ Graphtec manual for GP-GL)

### PR DESCRIPTION
**Pull request by Snow4DV**
I've got a graphtec plotter (MP4300) on my hands and there was a full GP-GL command set manual that may help you.
Note that it's quite old (late 80-s - early 90-s) so it is missing lots of stuff probably added to newer machines
but still makes many commands more clear:
https://github.com/Snow4DV/graphtec-gp-gl-manual/raw/main/Manual.pdf (shrinked to 20mb)
https://drive.google.com/file/d/1B3RUKR-3AUZ70lLAzPTq8G_it09QH3mp/view?usp=sharing (init 60mb)

### CODE REVIEW

**Comment by t0b3** [comment]
That's very helpful and great news. 
Can you fix the indent to fit the `Comments` column? This can help the reader to better understand.

**Comment by t0b3** [comment]
You may just push more commits to your repo, this will update the PR you made...
(If you like you can also squash and force push)

**Comment by Snow4DV** [comment]
> That's very helpful and great news. Can you fix the indent to fit the `Comments` column? This can help the reader to better understand.

Yeah, np, done

**Comment by t0b3** [comment]
@Snow4DV can you ensure all lines belonging to column `Comments` start at indent 60.
Currently they are hanging back and polluting `Name`. 
image

NB: I do care less about line length...

**Comment by Snow4DV** [comment]
> 

Done, indent was messed a bit before so i just kept it, now should be fine

**Comment by t0b3** [comment]
Well done, looks nice  :+1:

**Pull request merged**
