### PR TITLE
Portrait 3 works as well

### PR DESCRIPTION
**Pull request by maclomhair**
I just tried the extension with the portrait 3 and it seems to work quite well. I haven't tested thoroughly, though.

(Also this fixes a small typo in the "Supported Devices" heading)

### CODE REVIEW

**Comment by miggland** [comment]
I disagree - since setting the depth of the autoblade does not work by default. 

When sending the command 
`dev.send_command(tool.depth(1))`
manually, it works.

It seems this is because the Product ID is not in 'PRODUCT_LINE_CAMEO3_ON' and thus the command is not sent during setup.

The Product ID on my Portrait 3 seems to be 4410 (0x113a)

**Comment by t0b3** [comment]
@maclomhair @miggland thanks a lot for your contribution. I will happily add new hardware to the list.
Before we add it I would like you to help in adding the device to https://github.com/fablabnbg/inkscape-silhouette/blob/5a19eb4526d96371ff61683aa6e31f5bf6c5c537/silhouette/Graphtec.py#L141 and help out with testing whether it shall belong to a list (i.e. CAMEO3_ON or what else) to ensure the right commands are triggered.
Thanks a lot for your tests in advance as I don't have any such device.

**Comment by miggland** [comment]
Well, I can give you this straight away:

`Bus 001 Device 006: ID 0b4d:113a Graphtec America, Inc.`

It has an autoblade, only one tool holder. 

This works fine:
`
tool = SilhouetteCameoTool(1)
dev = SilhouetteCameo()
dev.send_command(tool.depth(1))
dev.send_command(tool.depth(5))
dev.send_command(tool.depth(10))
`

I'm not sure what else I'm supposed to test (haven't noticed anything else not working so far..)

**Comment by t0b3** [comment]
I'd like to receive a patch which adds `PRODUCT_ID_SILHOUETTE_PORTRAIT3` definition and specific case handling (if/else ...) for your device.

**Comment by mikhailmihalkov** [comment]
Tried to run Silhouette Portrait 3 and it does not work on win7-10 and linux blade makes 1 pass and in 2-3 seconds stops... Apparently, the firmware was changed in the new model and the python code is not suitable... Who has a point?

**Comment by t0b3** [comment]
@mikhailmihalkov thanks a lot for your feedback. I guess this will help. Did you try `--force_hardware` with any modern Silhouette Plotter?

**Comment by mikhailmihalkov** [comment]
log 1 and log 2 is a square cutting from Silhouette Studio Portrait 3

**Comment by mikhailmihalkov** [comment]
[log 1.txt](https://github.com/fablabnbg/inkscape-silhouette/files/8115299/log.1.txt)
[log 2  Portrait 3.txt](https://github.com/fablabnbg/inkscape-silhouette/files/8115300/log.2.Portrait.3.txt)

**Comment by mikhailmihalkov** [comment]
Result dump - wireshark usb dump
[usb_dump_Silhouette Portrait3.zip](https://github.com/fablabnbg/inkscape-silhouette/files/8116748/usb_dump_Silhouette.Portrait3.zip)

**Comment by mikhailmihalkov** [comment]
t0b3  https://github.com/mossblaser/py_silhouette/tree/master/test I checked with this library portrait 3 and it works passes the test successfully

**Comment by mikhailmihalkov** [comment]
> @mikhailmihalkov большое спасибо за ваш отзыв. Думаю, это поможет. Пробовали ли вы использовать `--force_hardware`какой-либо современный плоттер Silhouette?
https://github.com/mossblaser/py_silhouette/tree/master/test Я проверил с этой библиотекой портрет 3, и она работает, успешно проходит тест

**Comment by mikhailmihalkov** [comment]
> @mikhailmihalkov thanks a lot for your feedback. I guess this will help. Did you try `--force_hardware` with any modern Silhouette Plotter?
https://github.com/mossblaser/py_silhouette/tree/master/test I checked with this library portrait 3 and it works passes the test successfully

**Comment by t0b3** [comment]
@mikhailmihalkov what according to your tests needs to be adapted in https://github.com/fablabnbg/inkscape-silhouette/blob/5a19eb4526d96371ff61683aa6e31f5bf6c5c537/silhouette/Graphtec.py in order to work properly? your PR is welcome...

**Comment by ktosiek** [comment]
I can confirm Portrait 3 mostly works without additional changes, but to get AutoBlade working you'll also need my PR: #174

**Pull request merged**
