### PR TITLE
PEP8.   No more mixed tabs and spaces.  Update Print statements to be Py3 compatible

### PR DESCRIPTION
**Pull request by Cabalist**
Hello! 

Thank you for your work on this.   We just got a Silhouette Curio in the shop and I'm seeing if your plugin is compatible.  While reading through the code I did some minor cleanup to make it more PEP8 compliant.   There should be no functionality change in this PR just cleanup.   

Thanks!

### CODE REVIEW

**Comment by EtherGraf** [comment]
Thanks for sharing your work with us 

I definitly appreciate the work with the print functions to make it compatible with python3. 
Also I know, there is some mixture between tabs and blanks, which need cleanup.

But I am not sure, if it is a good idea to insert a lot of blanks between the operators only for code readability. This generates a lots of diffs for most of the code.

**Comment by Cabalist** [comment]
Hey there,

Thanks for the feedback!  I'm happy to break this up in to smaller chunks if that would be preferred.  Also you can view changes in github without whitespace by adding `?w=1` to the end of the urls i.e. [https://github.com/fablabnbg/inkscape-silhouette/pull/65/files?w=1](https://github.com/fablabnbg/inkscape-silhouette/pull/65/files?w=1)

I am a proponent to PEP8 including whitespace around operators to increase readability.  I find myself reading code 80% of the time and writing it 20% of the time and having a consistent style speeds up bug fixes and changes.

**Comment by EtherGraf** [comment]
I would really prefer to split the two themes phyton3 and pep8.
If you send a separate pull request for python3 compatibility i am happy to merge it. 

Before merging your pep8 thing all other pull request should be merged, because I expect a lot of conflicts afterwards.

**Comment by t0b3** [comment]
py3 compatiblity: done by #94

**Comment by t0b3** [comment]
@Cabalist  huh, we reworked lots of code recently. thus we might need an updated PR...
you may choose to reopen this or a new one

**Pull request closed without merging**
