### PR TITLE
Move cut path dump into log file and separate "dry run" behavior from "path dump"

### PR DESCRIPTION
**Pull request by gwhitney**
This PR is intended ultimately to replace #139. I have created it to divide the commit that made that PR into smaller self-contained commits as requested in the feedback. I am taking the liberty of submitting those commits one at a time through this PR because I am not sure how else to run the test suite. Thanks for your understanding, and if there's a different process you prefer I use please just let me know. I will remove the (WIP) designation and close #139 once all of the functionality there is incorporated here.

### CODE REVIEW

**Comment by t0b3** [comment]
I guess you meant #138 instead, right?

**Comment by gwhitney** [comment]
Yup. And per your comment in #138, I will finish up this PR with one more commit, to move the dump into the log and modify misc/read_dump.py to handle logs as well as old dumps.

**Comment by t0b3** [comment]
OK, just tell me when you're done with it...

**Comment by gwhitney** [comment]
OK, I think this portion is ready. Performing a dry run and dumping the cut paths are now separately selectable behaviors, so you can dump the cut paths from a live run if you want. The cut paths go into the log file, and misc/read_dump.py is updated so that it will handle log files (and in fact try to find the log file from inkscape's preferences, at least on Linux). Let me know what you think and then I will proceed from here.

**Comment by gwhitney** [comment]
Oh, I also added some faint directional arrows and a start (green) and end (red) indicator to the display in misc/read_dump.py -- I wish I had known about read_dump when I was working on the orientations, it would have made life much easier!

**Pull request merged**
