### PR TITLE
chore: prep all changes for switching primary branch to main

### PR DESCRIPTION
**Pull request by gwhitney**
This is not _exactly_ a pull request to main. I am filing this pursuant to the request in #160. The idea is that it should be possible simply to push/pull (I am no git expert) the _branch_ gwhitney/inkscape-silhouette main into the base repository as its own branch (no effect on master) and then subsequently switch to main as the primary branch in the base repository, and (hopefully) all will be well. (Frankly I was not quite sure how to test such a thing, but I believe I took care of everything necessary.)  If there are any problems I am happy to help further.

One note: in making this change I noticed for the first time doc/more_commands.txt. I copied the last tiny bit of information from it that was not already in Commands.md, and then just deleted the file, as it had become redundant. There is still redundancy/unclarity of organization between Commands.md and doc/commands.md, but this is not the opportunity to deal with that (and I am not sure what the maintainers would want in this respect). However, it seemed worth deleting doc/more_commands.txt at this point because it contained a stale reference into "master" and was in addition almost entirely redundant with the two .md files.

### CODE REVIEW

**Comment by t0b3** [comment]
can you make a second PR to remove `doc/more_commands.txt` and mention your thought on that in the commit msg?

**Comment by gwhitney** [comment]
Sure, so just to be clear: you want me to remove the changes to Command.md and the deletion of doc/more_commands.txt from this PR, and then re-file those changes as a separate PR once this has been processed? Happy to do that, please just confirm that's the desired plan.

**Comment by t0b3** [comment]
exactly that's it.

**Comment by gwhitney** [comment]
Ok, the requested mods to this "PR" have been made. When the dust settles on this, I'll do a micro-PR with the one adjustment to Commands.md and deleting doc/more_commands.txt (but I was not planning on attacking the organization/overlap of Commands.md vs. doc/commands.md unless you have a specific direction you want me to go with that).

**Comment by t0b3** [comment]
@EtherGraf @jnweiger do you agree to switch `master` to `main` ?
 - If yes can you rename the [master branch](https://github.com/fablabnbg/inkscape-silhouette/branches) to `main`, as I don't have the permission to do so. 
 - If no we would most probably drop this PR...

**Comment by EtherGraf** [comment]
I have no objectives against renaming the master branch to main branch. 
But i am no git or github expert at all and do not know how to rename a branch. 
Nor do i know, if I have the permissions. I have to look.

One thing to consider: 
If we rename the branch, will then everyone have to recheckout this new branch?

**Comment by gwhitney** [comment]
The documentation at https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch has answers to all of EtherGraf's questions (except for who has the permissions for renaming in this repo, of course ;-).

**Comment by EtherGraf** [comment]
I have just read the documantation and checked my permissions. I do not have the button to rename the branch.
Seems the renaming needs to be done by the owner @jnweiger

**Comment by gwhitney** [comment]
Not sure how often the owner is able to look in on this project; should I presume this renaming will happen at some point? I've been a bit reluctant to do much on this in case the primary branch changing might disrupt working with a branch in progress.

**Review by jnweiger — APPROVED** [review]
Absolutely no objection. 
Let's move to main.

Sorry for not looking for so long.
I do not track notifications on github. I mostly see them coming in by mail. But if its a busy day, I miss quite a few mail.

**Comment by t0b3** [comment]
@jnweiger ready, you may rename the branch to `main` now...

**Comment by jnweiger** [comment]
Done. Everybody needs to update their local repos now.
If you have a clean working copy, a simple `git checkout main` does it. Otherwise this is what github suggests:

image

**Pull request merged**
