### PR TITLE
Add cutting mat templates for Curio

### PR DESCRIPTION
**Pull request by CarlosGS**
image

### CODE REVIEW

**Comment by t0b3** [comment]
@CarlosGS feel free to sniff your usb connection with silhouette studio and add your cutting mat size as parameter... similar to #164

**Comment by t0b3** [comment]
@CarlosGS can you check the product ID of your Curio and add another PR to enhance this list...

https://github.com/fablabnbg/inkscape-silhouette/blob/fd43c60d0a25de226005f397004643b79921014f/silhouette/Graphtec.py#L130-L139

**Comment by CarlosGS** [comment]
Hi, yes! Work in progress in https://github.com/fablabnbg/inkscape-silhouette/issues/36#issuecomment-1250416125
We need some time for the author to sumbit a PR but it will be done!
Thank you :)

**Comment by t0b3** [comment]
great news :rocket: in case the author isn't reactive you may go on and submit your work...

**Pull request merged**
