### PR TITLE
Registrationmarks

### PR DESCRIPTION
**Pull request by EtherGraf**
I have created a branch registrationmarks, in which I got the regmark functionality to work. 

My silhouette portrait has succesfully searched and found the registration marks. It's tested with Ubuntu 14.04. No idea if this works on a cameo too. Needs testing.

To get it working, I had to pull in some changes from Alexander Senger, which sets the default coordinate system from landscape to portrait mode. 

To plot with registration marks do the following:
1. Open the document examples/registration-marks.svg
2. Insert your cutting paths and graphics.
3. Printout the whole document including registration marks.
4. Select your cutting paths in the document, but exclude regmarks and graphics.
5. Set or ensure the correct values (offset/width/height) on the regmark tab.
6. Enable 'Document has registration marks' and 'Search for registration marks'
7. Start cut.

The plotter will search the registration marks at the given positions. If it founds the marks, they will serve as accurate reference and define the origin. Therefore it is necessary to set the correct offset values of the mark. As a result the cut will go precisely along the graphics.

A further improvement (not yet implemented) would be automatic detection of the regmarks in the svg by ID, so it would not be necessary to set the numbers by hand.

### CODE REVIEW

**Comment by jnweiger** [comment]
Hey @EtherGraf thanks for working on regmarks support!

I am afraid I broke your PR by allowing other changes to happen meanwhile. 
Is it easy for you to try a rebase, or should we try a walk through and merge manually?

**Comment by EtherGraf** [comment]
I am no git expert, so I cannot overview the implications of a rebase. 
But I think it should be no big problem for me to merge the latest 
changes into my regmark branch.

Note that my work is based partly on changes from Alexander Senger, 
which was PR #21 too.
Maybe you should look at this first?

I will have a look later.

Am 30.08.2016 um 18:54 schrieb Jürgen Weigert:

> Hey @EtherGraf thanks for working on regmarks support!
> 
> I am afraid I broke your PR by allowing other changes to happen meanwhile.
> Is it easy for you to try a rebase, or should we try a walk through and merge manually?

**Comment by jnweiger** [comment]
Same with PR#21. unfortunately.

**Comment by EtherGraf** [comment]
I have tried merging yout current master into my local regmarks branch. 
It was only 8 lines to edit by hand. If it does help you, I can push 
this updated branch to github in the next days.

I am not sure which is the cleanest way to include this branch into your 
master as my local repository has lots of trial branches and remerges.

**Comment by jnweiger** [comment]
@EtherGraf I am inviting you to directly push here. How about that? 
https://github.com/fablabnbg/inkscape-silhouette/invitations
Please let me know if that is helpful in this case.

**Comment by EtherGraf** [comment]
Just released the merged regmarks branch. I had no time to do any tests, but expect no serious problems. At weekend I will have more time to continue with this. 
Thank you for your invitation, I will see if it is usefull.

**Comment by jnweiger** [comment]
Hey great work. Thanks. 
Could you please check what thappend to the return_home code? I have fragments in https://github.com/fablabnbg/inkscape-silhouette/blob/master/silhouette/Graphtec.py
but in your branch it seems to be missing. I believe it was functional with my silhoeutte 1 some time ago.

**Comment by EtherGraf** [comment]
I remember that something on the return to home was changed with the 
patches imported from Alexander. I had to patch this code, but finally 
it worked for me.

At the moment I'm a little short at time, so please excuse me till 
weekend, then I will have more time to investigate.

**Comment by EtherGraf** [comment]
@jnweiger 
To answer your question 2 months ago about the return_home code: It was removed by the patches from Alexander Wenger and later replaced by a new option 'endposition'. See PR #21
Should the existing interface be preserved or could it be replaced with the new one?

**Pull request merged**
